#!/bin/sh
# $Source$
# $State$
#
# Script to build a distribution package.

set -e
PACKAGE=spey
	
if [ "$1" = "" ]; then
	echo "Please specify a version number!"
	exit 1
fi

if [ -d ../$PACKAGE-$1 ]; then
	echo "I think you've already generated version $1."
	exit 1
fi

mkdir ../$PACKAGE-$1
cp -a --parents \
	./COPYING \
	./README \
	./WHITELIST \
	./doc/spey.8 \
	./doc/speyctl.8 \
	./pm \
	./pmfile \
	./pmlib/bin2c.pm \
	./pmlib/c.pm \
	./pmlib/utils.pm \
	./scripts/cron.d.script \
	./scripts/init.d.script \
	./src/Exception.cc \
	./src/Exception.h \
	./src/Logger.cc \
	./src/Logger.h \
	./src/SQL.cc \
	./src/SQL.h \
	./src/Settings.cc \
	./src/Settings.h \
	./src/Socket.cc \
	./src/Socket.h \
	./src/SocketAddress.cc \
	./src/SocketAddress.h \
	./src/SocketServer.cc \
	./src/SocketServer.h \
	./src/Statistics.cc \
	./src/Statistics.h \
	./src/Threadlet.cc \
	./src/Threadlet.h \
	./src/base64.cc \
	./src/common.h \
	./src/main.cc \
	./src/spey/MessageProcessor.cc \
	./src/spey/MessageProcessor.h \
	./src/spey/Parser.cc \
	./src/spey/Parser.h \
	./src/spey/SMTPCommand.cc \
	./src/spey/SMTPCommand.h \
	./src/spey/SMTPResponse.cc \
	./src/spey/SMTPResponse.h \
	./src/spey/ServerProcessor.cc \
	./src/spey/ServerProcessor.h \
	./src/spey/SpeyCLI.cc \
	./src/spey/SpeyCLI.h \
	./src/spey/auth.cc \
	./src/spey/greylist.cc \
	./src/spey/main_spey.cc \
	./src/spey/rbl.cc \
	./src/spey/spey.h \
	./src/speyctl/SpeyCtlCLI.cc \
	./src/speyctl/SpeyCtlCLI.h \
	./src/speyctl/init.sql \
	./src/speyctl/main_speyctl.cc \
	./src/speyctl/purge.sql \
	./src/speyctl/statsreset.sql \
	./src/version.cc \
	\
	../$PACKAGE-$1

(cd .. && tar cvf $PACKAGE-$1.tar.bz2 --bzip2 $PACKAGE-$1)

echo ""
echo "Done --- but did you remember to update the version number in the README?"

