#! /bin/sh
# /etc/cron.daily/spey
# Experimental cron.d script for purging the spey database.
#
# Copyright (C) 2011 David Given
# You may distribute under the terms of the GNU General Public
# License version 2 as specified in the file COPYING that comes with the
# Spey distribution.
#
# $Source: /cvsroot/spey/spey/scripts/init.d.script,v $
# $State: Exp $

set -e

DAEMON=/usr/sbin/speyctl

[ -x $DAEMON ] || exit 0

$DAEMON purge
